In [43]:
import pandas as pd
#importing module
from sklearn.preprocessing import LabelEncoder
#MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
#StandardScaler
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_excel("/content/ML_data.xlsx") # file path

In [4]:
df.sample(5)

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
2,103,CSE,91,88.0,15,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
0,101,CSE,85,78.0,12,0,Female,Pass
3,104,ECE,74,NaN,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

Features

In [6]:
X=df.drop("Final_Result",axis=1)

In [8]:
X

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender
0,101,CSE,85,78.0,12,0,Female
1,102,IT,62,45.0,5,2,Male
2,103,CSE,91,88.0,15,0,Female
3,104,ECE,74,NaN,8,1,Male
4,105,IT,55,39.0,4,3,Female

Target

In [7]:
y=df["Final_Result"]

In [9]:
y

0    Pass
1    Fail
2    Pass
3    Pass
4    Fail
Name: Final_Result, dtype: object

find null values

In [10]:
df.isnull() # null values in table

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False

where null value present in the table

In [13]:
df.isnull().sum() # null values in column

Student_ID        0
Department        0
Attendance        0
Internal_Marks    1
Study_Hours       0
Backlogs          0
Gender            0
Final_Result      0
dtype: int64

using mean the null value is replaced

In [16]:
df["Internal_Marks"].fillna(df['Internal_Marks'].mean())

0    78.0
1    45.0
2    88.0
3    62.5
4    39.0
Name: Internal_Marks, dtype: float64

Mean Imputation

In [17]:
df["Internal_Marks"]=df["Internal_Marks"].fillna(df['Internal_Marks'].mean())

In [18]:
df["Internal_Marks"]

0    78.0
1    45.0
2    88.0
3    62.5
4    39.0
Name: Internal_Marks, dtype: float64

Median Imputation

In [20]:
df["Internal_Marks"]=df["Internal_Marks"].fillna(df['Internal_Marks'].median())

In [21]:
df["Internal_Marks"]

0    78.0
1    45.0
2    88.0
3    62.5
4    39.0
Name: Internal_Marks, dtype: float64

In [22]:
df.head()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,62.5,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

converting gender female as 0, male as 1

In [26]:
encoder=LabelEncoder() # coverting gender into numeric value using Label encoding

In [27]:
encoder.fit_transform(df["Gender"])

array([0, 1, 0, 1, 0])

In [29]:
df["Gender_encoded"]=encoder.fit_transform(df["Gender"])

In [34]:
df[["Gender","Gender_encoded"]]

   Gender  Gender_encoded
0  Female               0
1    Male               1
2  Female               0
3    Male               1
4  Female               0

In [28]:
df["Gender"]

0    Female
1      Male
2    Female
3      Male
4    Female
Name: Gender, dtype: object

In [31]:
encoder.fit_transform(df["Department"]) # coverting dept into numeric values

array([0, 2, 0, 1, 2])

In [32]:
df["Department"] # display dept table

0    CSE
1     IT
2    CSE
3    ECE
4     IT
Name: Department, dtype: object

One_Hot encoding

In [33]:
pd.get_dummies(df,columns=["Department"]) # one-hot encoding

,Student_ID,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result,Gender_encoded,Department_CSE,Department_ECE,Department_IT
0,101,85,78.0,12,0,Female,Pass,0,True,False,False
1,102,62,45.0,5,2,Male,Fail,1,False,False,True
2,103,91,88.0,15,0,Female,Pass,0,True,False,False
3,104,74,62.5,8,1,Male,Pass,1,False,True,False
4,105,55,39.0,4,3,Female,Fail,0,False,False,True

In [39]:
scaler=MinMaxScaler()
scaler.fit_transform(df[["Study_Hours"]]) # normalization

array([[0.72727273],
       [0.09090909],
       [1.        ],
       [0.36363636],
       [0.        ]])

Normalization - MinMaxScaler

Normalization commonly scales values into a fixed range, often 0-1.

In [40]:
scaler=MinMaxScaler()
df["Study_Hours_scaled"]=scaler.fit_transform(df[["Study_Hours"]])

In [41]:
df[["Study_Hours","Study_Hours_scaled"]]

   Study_Hours  Study_Hours_scaled
0           12            0.727273
1            5            0.090909
2           15            1.000000
3            8            0.363636
4            4            0.000000

Standardization

https://medium.com/@rubinapaudelduhh/standardscaler-in-machine-learning-vs-z-score-in-statistics-f5babbb97455

In [45]:
std_scaler=StandardScaler()
std_scaler.fit_transform(df[['Study_Hours']])

array([[ 0.76802458],
       [-0.91202919],
       [ 1.48804762],
       [-0.19200614],
       [-1.15203687]])

In [47]:
std_scaler = StandardScaler()
df["Study_Hrs_std_scaled"] = std_scaler.fit_transform(df[['Study_Hours']])

In [48]:
df["Study_Hrs_std_scaled"].mean()

np.float64(-1.7763568394002506e-16)